FROM httpd:2.4

# apache web server - httpd 

COPY . /usr/local/apache2/htdocs/

# in cmd run 'docker build . -t myweb:1' 
# then 'docker run -p 8080:80 myweb:1' 
# go to http://localhost:8080 to view webpage
# Ctrl + C to stop container. / 8080:80 = source:destination
